/**
 * midnight/config.js — realDeal endpoints + network identity.
 *
 * Defaults target the LOCAL midnight-local-dev stack running on Penny:
 *   docker compose up in /home/js/utils_Midnight/midnight-local-dev
 *
 * Override via Vite env vars (.env.local) when deploying to a public
 * network. Mirrors the docs/MIDNIGHT_LOCAL_DEV_AND_ECOSYSTEM_2026-05-13.md
 * service / port table.
 */

const env = import.meta.env || {};

export const NETWORK_ID = env.VITE_NETWORK_ID || 'undeployed';

export const ENDPOINTS = {
  node: env.VITE_NODE_URL || 'http://localhost:9944',
  indexer: env.VITE_INDEXER_URL || 'http://localhost:8088/api/v3/graphql',
  indexerWs:
    env.VITE_INDEXER_WS_URL || 'ws://localhost:8088/api/v3/graphql/ws',
  proofServer: env.VITE_PROOF_SERVER_URL || 'http://localhost:6300',
};

// Where the compiled Compact bindings live, relative to the repo root.
// (See realDeal/contracts/managed/proof-or-bluff/ — generated by compactc.)
export const CONTRACT_BINDINGS_PATH = '@pob/contract';
export const ZKIR_DIR = '@pob/zkir';

// Filled in after the first `createMatch` deploys the contract.
// Persisted to localStorage so the page survives a reload.
const CONTRACT_ADDRESS_KEY = 'pob:realdeal:contract-address';

export function getContractAddress() {
  if (typeof window === 'undefined') return null;
  return window.localStorage.getItem(CONTRACT_ADDRESS_KEY);
}

export function setContractAddress(address) {
  if (typeof window === 'undefined') return;
  if (address) {
    window.localStorage.setItem(CONTRACT_ADDRESS_KEY, address);
  } else {
    window.localStorage.removeItem(CONTRACT_ADDRESS_KEY);
  }
}
