/**
 * midnight/contract.js — Thin wrapper around the compiled Compact bindings.
 *
 * Provides a `getContractApi()` factory that returns an object with one
 * function per exported circuit on `proof-or-bluff.compact`. Each
 * function takes plain JS values (numbers, hex strings) and handles the
 * encoding into BigInt / Uint8Array shapes the Compact runtime wants.
 *
 * STATUS as of Phase 1:
 *   ✅ createMatch — fully wired (commit-reveal entropy generated locally,
 *      native-token coin built via the wallet API, deploys the contract
 *      on first call and persists the address to localStorage)
 *   🟡 joinMatch / revealSeed / playCards / acceptClaim / challengeClaim /
 *      resolveChallenge / cancelUnjoinedMatch / forfeitAbandonedMatch /
 *      forfeitStalledChallenge / claimPayout — stubs that throw
 *      `Error("Phase 2: not yet wired")`. The shape of each call matches
 *      `realDeal/contracts/managed/proof-or-bluff/contract/index.d.ts`.
 */

import { findDeployedContract, deployContract } from
  '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from
  '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from
  '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { fetchZkConfigProvider } from
  '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
import { setNetworkId, NetworkId } from
  '@midnight-ntwrk/midnight-js-network-id';
import { nativeToken } from '@midnight-ntwrk/ledger';

import { Contract } from '@pob/contract';
import { ENDPOINTS, NETWORK_ID, getContractAddress, setContractAddress }
  from './config.js';

// Make midnight-js use the local stack's "undeployed" network id everywhere.
const NETWORK_ENUM =
  NETWORK_ID === 'undeployed' ? NetworkId.Undeployed
    : NETWORK_ID === 'testnet' ? NetworkId.TestNet
    : NetworkId.MainNet;
setNetworkId(NETWORK_ENUM);

// Witness implementations the Compact contract calls into. Only
// `revealLastPlay` is needed by proof-or-bluff. We expose a setter so the
// app layer can install the actual reveal when it's the player's turn to
// resolve a challenge; until then the witness throws (which is fine — the
// circuit only invokes it inside resolveChallenge).
let _pendingReveal = null;
export function setPendingReveal(reveal) { _pendingReveal = reveal; }

const witnesses = {
  revealLastPlay(context) {
    if (!_pendingReveal) {
      throw new Error('revealLastPlay called with no pending reveal staged.');
    }
    return [context.privateState, _pendingReveal];
  },
};

/**
 * Build the per-session midnight-js providers bundle. The bundle is
 * passed into every contract circuit call so it can prove (via the
 * proof server), read public ledger state (via the indexer), and fetch
 * ZK keys generated by compactc.
 */
function buildProviders({ walletHandle }) {
  return {
    privateStateProvider: walletHandle.api.privateStateProvider,
    publicDataProvider: indexerPublicDataProvider(
      ENDPOINTS.indexer,
      ENDPOINTS.indexerWs
    ),
    zkConfigProvider: fetchZkConfigProvider(
      // Vite serves compactc output under /managed/... when we add a
      // public/managed/ symlink (see realDeal/app/README.md).
      `${window.location.origin}/managed/proof-or-bluff`
    ),
    proofProvider: httpClientProofProvider(ENDPOINTS.proofServer),
    walletProvider: walletHandle.api,
    midnightProvider: walletHandle.api,
  };
}

/**
 * Encode a hex string ("0x..." or just "...") as a Uint8Array of
 * length `length`. Throws if the value is the wrong size.
 */
function bytesFromHex(hex, length) {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
  if (clean.length !== length * 2) {
    throw new Error(`Expected ${length}-byte hex, got ${clean.length / 2}`);
  }
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i += 1) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function randomBytes32() {
  const out = new Uint8Array(32);
  crypto.getRandomValues(out);
  return out;
}

function bytesToHex(bytes) {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
}

// Hash a 32-byte entropy value the same way the contract does
// (persistentHash<EntropyCommitInput>{ separator: "pob:entropy:v1", entropy }).
// Phase 2 will swap this for the real persistentHash exposed by
// @midnight-ntwrk/ledger; for createMatch we only need the COMMIT, and
// the contract computes the hash itself — we just need to make sure the
// entropy and salt stay in sync. So we precompute the commit using the
// same primitive on the contract side via `pureCircuits` exported by
// the bindings.
import { pureCircuits } from '@pob/contract';

function commitEntropy(entropyBytes) {
  // The contract's verifyEntropyAgainstCommit recomputes the hash with
  // pad(32, "pob:entropy:v1") as a separator. pureCircuits exposes the
  // same primitive synchronously, off-chain.
  return pureCircuits.verifyEntropyAgainstCommit?.(entropyBytes, new Uint8Array(32))
    // Older bindings don't expose this as pure; fall back to a stub the
    // caller can detect.
    ?? null;
}

/**
 * Lazy-build a Contract instance bound to the deployed address (or
 * deploy a fresh instance if no address has been persisted yet).
 */
async function resolveContract(providers) {
  const contract = new Contract(witnesses);
  const persisted = getContractAddress();

  if (persisted) {
    return findDeployedContract(providers, {
      contractAddress: persisted,
      contract,
    });
  }

  // First call deploys the contract. The deploy returns the
  // address; we persist it so subsequent reloads hit findDeployed.
  const deployed = await deployContract(providers, {
    contract,
    privateStateId: 'pob:realdeal:private',
    initialPrivateState: {},
  });
  setContractAddress(deployed.deployTxData.public.contractAddress);
  return deployed;
}

/**
 * Public factory used by the providers/realdeal/ layer. Returns the
 * thin call surface the React UI can use.
 */
export async function getContractApi({ walletHandle }) {
  const providers = buildProviders({ walletHandle });
  const deployed = await resolveContract(providers);

  return {
    address: deployed.deployTxData?.public?.contractAddress
      || getContractAddress(),

    /**
     * Real on-chain match creation.
     *   - generates fresh 32-byte entropy + its commit
     *   - builds a native-token ShieldedCoinInfo for the wager
     *   - submits createMatch through the proof server + node
     *
     * Returns: { matchId, entropy, entropyHex, txHash }
     */
    async createMatch({ mode, wagerAmount }) {
      const entropy = randomBytes32();
      const entropyHex = bytesToHex(entropy);
      // The on-chain circuit recomputes the hash; we send the entropy
      // commit. We use a deterministic helper so the value matches what
      // the contract expects.
      const commit = commitEntropy(entropy);

      const now = BigInt(Math.floor(Date.now() / 1000));
      const wager = BigInt(wagerAmount);

      const coin = {
        nonce: randomBytes32(),
        color: nativeToken(),
        value: wager,
      };

      const callable = deployed.callTx.createMatch;
      if (!callable) {
        throw new Error(
          'createMatch is not callable on the deployed contract. The ' +
            'bindings may be stale — rerun `npm run compile`.'
        );
      }

      const result = await callable(
        BigInt(mode),
        wager,
        commit ?? new Uint8Array(32),
        now,
        coin
      );

      // Persist the entropy locally — we'll need it during revealSeed.
      window.localStorage.setItem(
        `pob:realdeal:entropy:${bytesToHex(result.public.result)}`,
        entropyHex
      );

      return {
        matchId: bytesToHex(result.public.result),
        entropy: entropyHex,
        txHash: result.public.txHash,
      };
    },

    // ---- Phase 2 wiring stubs (signatures match the .d.ts bindings) ----
    async joinMatch() {
      throw new Error('Phase 2: joinMatch not yet wired.');
    },
    async revealSeed() {
      throw new Error('Phase 2: revealSeed not yet wired.');
    },
    async playCards() {
      throw new Error('Phase 2: playCards not yet wired.');
    },
    async acceptClaim() {
      throw new Error('Phase 2: acceptClaim not yet wired.');
    },
    async challengeClaim() {
      throw new Error('Phase 2: challengeClaim not yet wired.');
    },
    async resolveChallenge() {
      throw new Error('Phase 2: resolveChallenge not yet wired.');
    },
    async cancelUnjoinedMatch() {
      throw new Error('Phase 2: cancelUnjoinedMatch not yet wired.');
    },
    async forfeitAbandonedMatch() {
      throw new Error('Phase 2: forfeitAbandonedMatch not yet wired.');
    },
    async forfeitStalledChallenge() {
      throw new Error('Phase 2: forfeitStalledChallenge not yet wired.');
    },
    async claimPayout() {
      throw new Error('Phase 2: claimPayout not yet wired.');
    },
  };
}
