import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import topLevelAwait from 'vite-plugin-top-level-await';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { execFile } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Tiny dev-only middleware: GET /api/proof-server-logs?tail=N returns
// the last N lines of `docker logs midnight-proof-server` as plain
// text. The realDeal UI polls this so the player can watch ZK proofs
// being generated live in the side panel while they play. Read-only,
// only mounted by the dev server, so it cannot leak into production.
function proofServerLogsPlugin() {
  return {
    name: 'pob-proof-server-logs',
    configureServer(server) {
      server.middlewares.use('/api/proof-server-logs', (req, res) => {
        const url = new URL(req.url || '/', 'http://localhost');
        const tail = Math.min(
          200,
          Math.max(1, Number(url.searchParams.get('tail') || 30))
        );
        execFile(
          'docker',
          ['logs', '--tail', String(tail), 'midnight-proof-server'],
          { timeout: 4000, maxBuffer: 1024 * 1024 },
          (err, stdout, stderr) => {
            res.setHeader('Content-Type', 'text/plain; charset=utf-8');
            res.setHeader('Cache-Control', 'no-store');
            if (err) {
              res.statusCode = 503;
              res.end(
                `proof-server unreachable: ${err.message}\n${stderr || ''}`
              );
              return;
            }
            // proof-server uses tracing -> stderr; combine streams in
            // chronological order.
            res.end(`${stderr || ''}${stdout || ''}`);
          }
        );
      });
    },
  };
}

// Proof or Bluff — realDeal Vite app. Port 3016 (demoLand owns 3015).
// Aliases let the Midnight SDK packages resolve correctly inside the
// browser bundle even when their internal deps reach for Node built-ins.
//
// vite-plugin-wasm + vite-plugin-top-level-await are required because
// @midnight-ntwrk/ledger-v8 (and a handful of other v8 SDK packages)
// ship as WASM modules with top-level-await initialization. Without
// these plugins Vite errors with: "ESM integration proposal for Wasm
// is not supported currently".
export default defineConfig({
  plugins: [react(), wasm(), topLevelAwait(), proofServerLogsPlugin()],
  resolve: {
    // Keep symlinks unresolved so the bindings imported via
    // src/contract/ keep their import paths anchored inside realDeal/app/,
    // where node_modules can satisfy @midnight-ntwrk/*.
    preserveSymlinks: true,
    alias: {
      // Compiled Compact bindings — generated by compactc into
      // realDeal/contracts/managed/proof-or-bluff/contract/.
      // realDeal/app/src/contract is a symlink to
      // realDeal/contracts/managed/proof-or-bluff. Importing through the
      // symlinked path lets the bindings resolve @midnight-ntwrk/* from
      // realDeal/app/node_modules.
      '@pob/contract': resolve(
        __dirname,
        './src/contract/contract/index.js'
      ),
      '@pob/zkir': resolve(
        __dirname,
        './src/contract/zkir'
      ),
    },
  },
  define: {
    // Some midnight-js packages still reference process.env at module init.
    'process.env': {},
    global: 'globalThis',
  },
  optimizeDeps: {
    // Only the WASM-backed ledger packages need to skip esbuild
    // pre-bundling (esbuild strips top-level-await, which breaks WASM
    // init). Everything else MUST be pre-bundled so CJS->ESM interop
    // works for transitive deps like `object-inspect` that several
    // midnight-js packages reach for.
    exclude: [
      '@midnight-ntwrk/ledger-v8',
      '@midnight-ntwrk/zswap',
      '@midnight-ntwrk/onchain-runtime',
    ],
    // Force-include CJS deps that midnight-js uses transitively, so
    // Vite synthesizes proper default exports for them.
    include: [
      'object-inspect',
      'side-channel',
      'qs',
    ],
    esbuildOptions: {
      target: 'es2022',
    },
  },
  build: {
    target: 'es2022',
    outDir: 'dist',
    sourcemap: false,
  },
  server: {
    port: 3016,
    host: true,
    strictPort: false,
  },
  preview: {
    port: 3016,
  },
});
