import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import topLevelAwait from 'vite-plugin-top-level-await';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Proof or Bluff — realDeal Vite app. Port 3016 (demoLand owns 3015).
// Aliases let the Midnight SDK packages resolve correctly inside the
// browser bundle even when their internal deps reach for Node built-ins.
//
// vite-plugin-wasm + vite-plugin-top-level-await are required because
// @midnight-ntwrk/ledger-v8 (and a handful of other v8 SDK packages)
// ship as WASM modules with top-level-await initialization. Without
// these plugins Vite errors with: "ESM integration proposal for Wasm
// is not supported currently".
export default defineConfig({
  plugins: [react(), wasm(), topLevelAwait()],
  resolve: {
    // Keep symlinks unresolved so the bindings imported via
    // src/contract/ keep their import paths anchored inside realDeal/app/,
    // where node_modules can satisfy @midnight-ntwrk/*.
    preserveSymlinks: true,
    alias: {
      // Compiled Compact bindings — generated by compactc into
      // realDeal/contracts/managed/proof-or-bluff/contract/.
      // realDeal/app/src/contract is a symlink to
      // realDeal/contracts/managed/proof-or-bluff. Importing through the
      // symlinked path lets the bindings resolve @midnight-ntwrk/* from
      // realDeal/app/node_modules.
      '@pob/contract': resolve(
        __dirname,
        './src/contract/contract/index.js'
      ),
      '@pob/zkir': resolve(
        __dirname,
        './src/contract/zkir'
      ),
    },
  },
  define: {
    // Some midnight-js packages still reference process.env at module init.
    'process.env': {},
    global: 'globalThis',
  },
  optimizeDeps: {
    // Only the WASM-backed ledger packages need to skip esbuild
    // pre-bundling (esbuild strips top-level-await, which breaks WASM
    // init). Everything else MUST be pre-bundled so CJS->ESM interop
    // works for transitive deps like `object-inspect` that several
    // midnight-js packages reach for.
    exclude: [
      '@midnight-ntwrk/ledger-v8',
      '@midnight-ntwrk/zswap',
      '@midnight-ntwrk/onchain-runtime',
    ],
    // Force-include CJS deps that midnight-js uses transitively, so
    // Vite synthesizes proper default exports for them.
    include: [
      'object-inspect',
      'side-channel',
      'qs',
    ],
    esbuildOptions: {
      target: 'es2022',
    },
  },
  build: {
    target: 'es2022',
    outDir: 'dist',
    sourcemap: false,
  },
  server: {
    port: 3016,
    host: true,
    strictPort: false,
  },
  preview: {
    port: 3016,
  },
});
